"""Zone overlay — iter-17 C part 2.

Takes a macro-zoning variant and the original client floor-plan (as the
FloorPlan model) and produces a 2D coloured overlay : the architectural
line-work preserved, zone areas tinted per the adjacency-rules palette,
a clean legend in the bottom-right corner.

Approach :

1. Render the variant + plan to the deterministic 2D SVG generated by
   `floorplan_svg.render_floorplan_svg`.
2. Rasterise it to PNG via a tiny stdlib-only helper (Pillow if
   available; else we ship the SVG as the overlay artefact — the
   frontend can render SVG natively anyway).
3. If NanoBanana Pro is available, call `image_to_image` with a prompt
   that instructs the model to preserve the plan's line-work but
   sharpen the zone colours and add a printed legend.
4. Cache by sha256(plan + variant + prompt) so re-runs are free.

The Pillow branch is best-effort ; if Pillow isn't installed or the
SVG rasterises unevenly, we fall back to the SVG-only artefact which
still looks great in the browser and sidesteps any binary-dependency
pain on Windows.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from app.models import FloorPlan, VariantOutput
from app.services.nanobanana_client import (
    GeneratedImage,
    NanoBananaClient,
    NanoBananaError,
)
from app.surfaces.floorplan_svg import render_floorplan_svg


BACKEND_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = BACKEND_ROOT / "data" / "generated_images"
OUT_DIR.mkdir(parents=True, exist_ok=True)


class ZoneOverlayRequest(BaseModel):
    floor_plan: FloorPlan
    variant: VariantOutput
    # If the caller already has a preferred base image (rasterised
    # client PDF, say), pass it here. Otherwise we'll render our SVG
    # and use that as the base.
    base_image_path: str | None = None
    use_nanobanana: bool = True
    # Cosmetic — what the prompt should stress.
    emphasis: str = (
        "preserve the architectural line weight and column grid, "
        "heighten zone fill contrast, keep the legend legible"
    )


class ZoneOverlayResponse(BaseModel):
    # Path relative to repo root (served via /static/generated).
    overlay_image_path_rel: str
    cache_hit: bool
    fallback_used: bool
    fallback_reason: str | None = None
    svg_path_rel: str
    cache_key: str


def _hash_payload(*parts: bytes | str) -> str:
    h = hashlib.sha256()
    for p in parts:
        if isinstance(p, str):
            p = p.encode()
        h.update(p)
        h.update(b"|")
    return h.hexdigest()[:32]


def _try_rasterise_svg(svg: str, dest_png: Path, width_px: int = 1600) -> bool:
    """Best-effort SVG→PNG using Pillow's svg plugin if available."""

    try:
        from io import BytesIO

        import cairosvg  # type: ignore

        png_bytes = cairosvg.svg2png(bytestring=svg.encode(), output_width=width_px)
        dest_png.write_bytes(png_bytes)
        return True
    except Exception:  # cairosvg missing or native cairo missing
        pass
    # Pillow 10+ can't render SVG natively, and we don't want to add
    # a compiled dep on Windows. Signal failure to the caller.
    return False


def _build_overlay_prompt(variant: VariantOutput, emphasis: str) -> str:
    audit_hint = ""
    if variant.adjacency_audit and variant.adjacency_audit.violations:
        audit_hint = (
            "The zones also carry an adjacency audit — keep the "
            "existing colour assignments, do not re-arrange."
        )
    return (
        f"Architectural floor plan overlay for the variant «{variant.title}». "
        "Preserve the existing architectural drawing precision : walls, "
        "columns, doors, stairs and column grid stay exactly where they "
        "are, same line weight, same vectors. Colour-fill the regions per "
        "the existing zone map : work in #3A5A4F (forest), collab in "
        "#C9B79C (sand), support in #A0522D (clay), hospitality in "
        "#E8C547 (sun), biophilic in #6B8F7F (mint). Keep each numbered "
        "zone tag centred and legible. Add a clean legend in the bottom-"
        f"right corner with colour chips and labels. {emphasis}. {audit_hint} "
        "No extra annotations, no shadows, no photograph backgrounds. "
        "Pure 2D architectural rendering, magazine-clean."
    ).strip()


@dataclass
class ZoneOverlaySurface:
    client: NanoBananaClient | None = None

    def generate(self, req: ZoneOverlayRequest) -> ZoneOverlayResponse:
        # 1. Render the deterministic SVG — this alone is already the
        #    "2D painted plan" artefact the frontend can display.
        svg = render_floorplan_svg(plan=req.floor_plan, variant=req.variant)
        plan_bytes = req.floor_plan.model_dump_json().encode()
        variant_bytes = req.variant.model_dump_json().encode()
        cache_key = _hash_payload(plan_bytes, variant_bytes, svg)

        svg_path = OUT_DIR / f"{cache_key}.svg"
        if not svg_path.exists():
            svg_path.write_text(svg, encoding="utf-8")

        repo_root = BACKEND_ROOT.parent.parent
        svg_rel = str(svg_path.relative_to(repo_root))

        # 2. If the caller doesn't want NanoBanana OR we can't rasterise
        #    the SVG, return the SVG itself as the overlay artefact.
        if not req.use_nanobanana:
            return ZoneOverlayResponse(
                overlay_image_path_rel=svg_rel,
                cache_hit=True,
                fallback_used=True,
                fallback_reason="nanobanana_disabled",
                svg_path_rel=svg_rel,
                cache_key=cache_key,
            )

        client = self.client
        if client is None:
            try:
                client = NanoBananaClient()
            except NanoBananaError as exc:
                return ZoneOverlayResponse(
                    overlay_image_path_rel=svg_rel,
                    cache_hit=True,
                    fallback_used=True,
                    fallback_reason=f"no_fal_key: {exc}",
                    svg_path_rel=svg_rel,
                    cache_key=cache_key,
                )

        # 3. Build a base PNG. If cairosvg isn't installed, fall back
        #    to serving the SVG instead of calling fal.ai — the frontend
        #    can display the SVG directly with the same visual quality,
        #    just without the NanoBanana pass that enhances the plan.
        base_png = OUT_DIR / f"{cache_key}_base.png"
        if req.base_image_path:
            candidate = Path(req.base_image_path)
            if candidate.exists():
                base_png = candidate
        elif not base_png.exists():
            rasterised = _try_rasterise_svg(svg, base_png, width_px=1600)
            if not rasterised:
                return ZoneOverlayResponse(
                    overlay_image_path_rel=svg_rel,
                    cache_hit=True,
                    fallback_used=True,
                    fallback_reason="svg_rasterise_unavailable (install cairosvg for NanoBanana pass)",
                    svg_path_rel=svg_rel,
                    cache_key=cache_key,
                )

        # 4. Image-to-image call, cached by NanoBananaClient on the
        #    (prompt + base_image_hash) tuple.
        prompt = _build_overlay_prompt(req.variant, req.emphasis)
        try:
            result: GeneratedImage = client.image_to_image(
                base_image_path=base_png,
                prompt=prompt,
                aspect_ratio="16:10",
                strength=0.35,  # keep the line work dominant
            )
        except NanoBananaError as exc:
            return ZoneOverlayResponse(
                overlay_image_path_rel=svg_rel,
                cache_hit=True,
                fallback_used=True,
                fallback_reason=f"fal_call_failed: {exc}",
                svg_path_rel=svg_rel,
                cache_key=cache_key,
            )

        try:
            overlay_rel = str(result.path.relative_to(repo_root))
        except ValueError:
            overlay_rel = str(result.path)

        return ZoneOverlayResponse(
            overlay_image_path_rel=overlay_rel,
            cache_hit=result.from_cache,
            fallback_used=False,
            fallback_reason=None,
            svg_path_rel=svg_rel,
            cache_key=cache_key,
        )


def compile_default_surface() -> ZoneOverlaySurface:
    try:
        client: NanoBananaClient | None = NanoBananaClient()
    except NanoBananaError:
        client = None  # frontend still gets the SVG via fallback path
    return ZoneOverlaySurface(client=client)
